spring:
    profiles.active: prod
---
springdoc:
    api-docs:
        enabled: false
    swagger-ui:
        enabled: false

apache:
    provider: ${PROVIDER}
    keystore: 
        type: ${KEYSTORE_TYPE}
        password: ${KEYSTORE_PASSWORD}
        alias: ${ENCRYPTION_USERNAME}
        file: ${KEYSTORE_PATH}

trdm:
    props-path: ${CLIENT_PROPS_FILE_PATH}
    encryption-username: ${ENCRYPTION_USERNAME}