version: 2.1

jobs:
  build:
    docker:
      - image: milmove/docker-mvn
        auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build
  release:
    docker:
      - image: milmove/docker-mvn
        auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build
      - run:
          name: Release
          command: |
            ARTIFACT_ID=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.artifactId -q -DforceStdout)
            VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
            JAR_NAME="target/$ARTIFACT_ID-$VERSION.jar"
            scripts/release $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME << pipeline.git.tag >> $JAR_NAME
      - run:
          name: Move jar and checksum to workspace
          command: |
            mkdir -p workspace
            # Grab jar name
            ARTIFACT_ID=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.artifactId -q -DforceStdout)
            VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
            JAR_NAME="target/$ARTIFACT_ID-$VERSION.jar"
            # Copy jar to workspace
            cp $JAR_NAME workspace/
            # Copy checksums to workspace
            cp checksums.txt workspace/checksums.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - checksums.txt
            - "/*.jar"
            - "target/*.jar"
      - attach_workspace:
          at: workspace
      - store_artifacts:
          path: workspace/checksums.txt
          destination: artifacts
      - store_artifacts:
          path: workspace/*.jar
          destination: artifacts
      - store_artifacts:
          path: workspace/target/*.jar
          destination: artifacts
workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
          - org-global
  release:
    jobs:
      - release:
          context:
          - org-global
          filters:
            branches:
              ignore: /^.*/
            tags:
              only: /^v.*/