version: 2.1

jobs:
  build:
    docker:
      - image: milmove/docker-mvn
        auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME
        environment:
          TEST_DB_HOST: localhost
          TEST_DB_NAME: test_db
          TEST_DB_USER: postgres
          TEST_DB_PORT: 5433
          TEST_DB_PASSWORD: mysecretpassword
          TEST_DB_URL: jdbc:postgresql://localhost:5433/test_db?user=postgres&password=mysecretpassword

    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build
  release:
    docker:
      - image: milmove/docker-mvn
        auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build
      - run:
          name: Release
          command: scripts/release $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME << pipeline.git.tag >>
      - run:
          name: Move zips and checksums to workspace
          command: |
            mkdir -p workspace
            cp deployment-package.stg.zip workspace/
            cp stg-checksums.txt workspace/
            cp deployment-package.prd.zip workspace/
            cp prd-checksums.txt workspace/
      - persist_to_workspace:
          root: workspace
          paths:
            - "*.zip"
            - "*.txt"
      - attach_workspace:
          at: workspace
      - store_artifacts:
          path: workspace/*.zip
          destination: artifacts
      - store_artifacts:
          path: workspace/*.txt
          destination: artifacts
workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - org-global
  release:
    jobs:
      - release:
          context:
            - org-global
          filters:
            branches:
              ignore: /^.*/
            tags:
              only: /^v.*/