version: 2.1

jobs:
  build:
    docker:
      - image: trussworks/gh-cli
        auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build
  release:
    docker:
      - image: trussworks/gh-cli
        auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build
      - run:
          name: Release
          command: scripts/release $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME << pipeline.git.tag >>
      - run:
          name: Move checksum to workspace
          command: |
            mkdir -p workspace
            cp checksums.txt workspace/checksums.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - checksums.txt
workflows:
  version: 2
  validate:
    jobs:
      - validate:
          context:
          - org-global
  build:
    jobs:
      - build:
          context:
          - org-global
  release:
    jobs:
      - release:
          context:
          - org-global
          filters:
            branches:
              ignore: /^.*/
            tags:
              only: /^v.*/