#!/bin/bash

set -eu -o pipefail

# Announce
echo "Packaging..."

# Build via sam
sam build
# Zip prd
zip -r deployment-package.prd.zip .aws-sam/build/SoapProxyFunction
# Overwrite build wsdl and then zip stg
cp -f .aws-sam/build/SoapProxyFunction/ReturnTableV7.stg.wsdl .aws-sam/build/SoapProxyFunction/ReturnTableV7.wsdl
zip -r deployment-package.stg.zip .aws-sam/build/SoapProxyFunction

# Announce and calculate checksum
echo "Packaging complete, saving as artifact."
echo "Calculating checksum."
sha512sum deployment-package.stg.zip > stg-checksums.txt
sha512sum deployment-package.prd.zip > prd-checksums.txt
ls