#!/bin/bash

set -eu -o pipefail

# Announce
echo "Packaging..."

# Build via sam
# Tests have been disabled during the build because more work needs to be completed to automate the pipelines for trdm
# sam build // This should be reinstated in B-20145 under E-05306
MAVEN_OPTS="-DskipTests=true" sam build

# Zip requires `cd` because if not it will compile the relative paths
# which means it will also zip .aws-sam/build/, breaking the deployment.
# Using -j makes it flat, ignoring .aws-sam/build/ but also
# ignoring the subdirectories which we need.

# Zip prd
cd .aws-sam/build/SoapProxyFunction
zip -r ../../../deployment-package.prd.zip .
cd ../../../


# Overwrite build wsdl
cp -f .aws-sam/build/SoapProxyFunction/ReturnTableV7.stg.wsdl .aws-sam/build/SoapProxyFunction/ReturnTableV7.wsdl

# Zip stg
cd .aws-sam/build/SoapProxyFunction
zip -r ../../../deployment-package.stg.zip .
cd ../../../

# Announce and calculate checksum
echo "Packaging complete, saving as artifact."
echo "Calculating checksum."
sha512sum deployment-package.stg.zip > stg-checksums.txt
sha512sum deployment-package.prd.zip > prd-checksums.txt
ls