#!/bin/bash

set -e -o pipefail

# Setup/how to run
usage() {
    echo "Usage: $0 <GITHUB_USER> <GITHUB_REPO> <NEW_TAG>"
    exit 1
}

[[ -z $1 || -z $2 || -z $3 ]] && usage
set -u

readonly GITHUB_USER=$1
readonly GITHUB_REPO=$2
readonly NEW_TAG=$3

# Pull jar from persisted workspace
JAR_NAME="workspace/$ARTIFACT_ID-$VERSION.jar"

gh release upload --clobber --repo "${GITHUB_USER}/${GITHUB_REPO}" $NEW_TAG $JAR_NAME checksums.txt
echo "Uploaded zipfile and checksums to GitHub Release with tag ${NEW_TAG}"