package trdm.returntableservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-10-17T18:18:34.829-04:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "ReturnTable",
                  wsdlLocation = "classpath:ReturnTableV7.wsdl",
                  targetNamespace = "http://trdm/ReturnTableService")
public class ReturnTable extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://trdm/ReturnTableService", "ReturnTable");
    public final static QName ReturnTableWSSoapHttpPort = new QName("http://trdm/ReturnTableService", "ReturnTableWSSoapHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("classpath:ReturnTableV7.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReturnTable.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:ReturnTableV7.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ReturnTable(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReturnTable(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReturnTable() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ReturnTable(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ReturnTable(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ReturnTable(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ReturnTableWSSoapHttpPort
     */
    @WebEndpoint(name = "ReturnTableWSSoapHttpPort")
    public ReturnTableWSSoapHttpPort getReturnTableWSSoapHttpPort() {
        return super.getPort(ReturnTableWSSoapHttpPort, ReturnTableWSSoapHttpPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReturnTableWSSoapHttpPort
     */
    @WebEndpoint(name = "ReturnTableWSSoapHttpPort")
    public ReturnTableWSSoapHttpPort getReturnTableWSSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(ReturnTableWSSoapHttpPort, ReturnTableWSSoapHttpPort.class, features);
    }

}
